### ISSUE TITLE
Finish dev-desktop rollout

### ISSUE THREAD

**Issue by jdno** [rust-lang/simpleinfra#142]
## Context

The dev desktops provide maintainers and contributors to the Rust Project with free access to high-powered cloud compute. They are part of the [Cloud Compute Program](https://foundation.rust-lang.org/news/2021-11-16-news-announcing-cloud-compute-initiative/) of the [Rust Foundation](https://foundation.rust-lang.org/).

A development instance for the dev desktops was deployed in early 2022, and used to develop scripts and tools for the users of the machines. In October, two production instances were deployed to AWS (see https://github.com/rust-lang/simpleinfra/pull/125).

## Tasks

The following tasks still need to be done to finish the rollout of the current generation of dev desktops. Future work such as scaling the project will be tracked in separate issues.

- [ ] Set git username and email in `init` script (https://github.com/rust-lang/simpleinfra/pull/110)
- [ ] Decommission the old instance(s)
- [ ] Document the worktree scripts
