### ISSUE TITLE
Write unit tests for `static.crates.io` function

### ISSUE THREAD

**Issue by jdno** [rust-lang/simpleinfra#401]
## Context

The crates on crates.io are stored in S3 and served to users through our Content Delivery Networks, most importantly Fastly. On Fastly, we are using their [Compute](https://www.fastly.com/documentation/guides/compute/) platform to run every request through a [custom Rust function](https://github.com/rust-lang/simpleinfra/tree/master/terragrunt/modules/crates-io/compute-static).

This function mainly has two responsibilities:

1. It handles the request, which means applying some rewrite rules and fetching the crate from S3.
2. It logs the request and sends it to the configured log destinations.

Since the function runs in WebAssembly, testing the function has been historically difficult. But Fastly provides more documentation now that might make it feasible to write unit tests for (some parts of) the function.

## Tasks

- [ ] Write (a few) unit tests for the function
- [ ] Document how to run them in local development
- [ ] Run the tests automatically as part of this repository's CI

## Resources

- [How to write Rust unit tests for your Compute application](https://www.fastly.com/blog/how-to-write-rust-unit-tests-for-your-compute-edge-application)
- [Rust on the Compute platform > Unit testing](https://www.fastly.com/documentation/guides/compute/rust/#unit-testing)
- https://github.com/fastly/Viceroy#usage-as-a-test-runner
