### ISSUE TITLE
Purge Fastly cache when publishing rustup

### ISSUE THREAD

**Issue by jdno** [rust-lang/simpleinfra#415]
We recently [realized](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/Rustup.20v1.2E27.2E1) that the cache on Fastly is not purged when a new version of `rustup` is released.

`rustup` is distributed via `static.rust-lang.org` as part of the same Fastly services as the Rust releases. Ideally, we therefore only purge cached versions of `rustup` and don't purge the whole cache. We already do this [for the Rust releases](https://github.com/rust-lang/simpleinfra/blob/54bd88a2e0dfd474ef7a0f349565b555469491a9/terragrunt/modules/release-distribution/fastly-static.tf#L72-L80) by setting [surrogate keys](https://www.fastly.com/documentation/guides/concepts/edge-state/cache/purging/#surrogate-key-purge) that we can granularly purge.

Fastly's purge APIs require authentication. We can generate a token that is scoped to the service and only grants permissions to purge content. The token can be stored in the parameter store on AWS, similar to other tokens that we already use.

## Tasks

- [ ] Set a surrogate key for requests to `/rustup/*`
- [ ] Create an authentication token for the release process and store it in SSM
- [ ] Extend [`sync-dist.py`](https://github.com/rust-lang/rustup/blob/master/ci/sync-dist.py) to [purge the surrogate key](https://www.fastly.com/documentation/reference/api/purging/#purge-tag)
