### ISSUE TITLE
Set up CDN for crates.io's download statistics

### ISSUE THREAD

**Issue by jdno** [rust-lang/simpleinfra#436]
The infra-team recently [created an S3 bucket](https://github.com/rust-lang/simpleinfra/pull/413) for crates.io so that it can export its daily downloads statistics from the database. The crates.io team wants to make these statistics publicly available, which requires us serve them through a CDN.

Two different options [have been discussed](https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/archiving.20.60version_downloads.60.20to.20S3/near/440480148):

1. Add the new bucket to `static.crates.io` as a new origin
2. Create a new CDN just for the statistics

No conclusion has been reached and resolving this discussion is one of the first tasks of this issue.

## Tasks

- [x] Explore both options and propose a solution to the infra-team
- [ ] Set up CDN in staging environment
- [ ] Confirm working functionality with crates.io team
- [ ] Set up CDN in production environment

**Comment by MarcoIeni** [comment]
I'll work on it!

**Comment by MarcoIeni** [comment]
In the following I will list pros (👍) and cons (👎) of each approach.
I'm writing them down to:
- confirm I understood the issue
- take an informed decision

> [!NOTE]
> Everyone, please bare in mind that I started this week and I'm not familiar with the current setup of crates.io infrastructure, so I might be missing some important details and I might be wrong in some of the points I'm making.
> So correct me if I'm wrong please 🙏

## Approach 1: Creating a new CloudFront distribution

Serve this new bucket as something like `downloads.crates.io`.
Proposed [here](https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/archiving.20.60version_downloads.60.20to.20S3/near/440490177).

### 👍 Easier way to track the traffic. 

We can easily track the traffic of the new distribution (we need to start tracking `downloads.crates.io`). So that we know that the traffic of `static.crates.io` only contains traffic of crates (not downloads).
This means there's no need to update the current dashboards that track the traffic of `static.crates.io`.

> [!NOTE]
> I might be totally wrong about this because maybe it's easier to reuse the same mechanism we have in place for `static.crates.io`.
> Maybe start tracking a new distribution takes a lot of work or resources.

### 👍 Reuse the same code

As JD said:

> right now we have a 1:1 mapping between buckets and distributions.

So this approach is consistent with the current setup because it doesn't break the 1:1 mapping we have for the other buckets.

We don't need to "invent" new terraform code, we can just copy-paste what we have.
This means we will complete this task sooner.

### 👎 More difficult to migrate to a single bucket

We created a new bucket for downloads because we didn't want to add new stuff to the legacy account.
However, we plan to move also the crates bucket to the new account eventually.
In this way, crates.io could have just one bucket for both crates and downloads, simplifying the configuration and code.

This point was also raised by Pietro:

> I would expect that soon(ish) we would migrate the actual crates to the new accounts, and then we can use a single bucket for everything

If we serve downloads from `downloads.crates.io`, and later the crates.io team decides to use one S3 bucket for both crates and downloads, it's an issue because we need to maintain the old `downloads.crates.io` distribution to keep compatibility with old clients that will be around (e.g. old cargo versions).

> [!NOTE]
> I'm not too sure about this point. Maybe `downloads.crates.io` could redirect to `static.crates.io` and we could remove the old distribution.
> But still, I wanted to mention this point anyway.

## Approach 2: Reuse `static.crates.io` 

Serve the new bucket as something like `static.crates.io/downloads/`.
Proposed [here](https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/archiving.20.60version_downloads.60.20to.20S3/near/440504019).

### 👍 Easier for the client

For the client point of view, it's easier to use the same domain for both crates and downloads.
In fact, to download a crate, clients use `https://static.crates.io/crates/<crate-name>/<crate-name>-<crate-version>.crate`.
Downloading crates from a URL like `https://static.crates.io/downloads/<something>` is easier than `https://downloads.crates.io/downloads/<something>` because you only need to deal with one domain.
This simplifies both the client code and the client configuration.

The same holds for alternative cargo registries because their implementation could be simpler with this approach.

### 👍 Maybe simpler

This setup is less complicated because we don't need to create a new CloudFront distribution.

As Pietro said:

> One less distribution to care about

However, it might require more implementation work because as explained above, this setup doesn't have the 1:1 mapping between buckets and distributions that we have for the other buckets.

The hope is that after the implementation phase, the code will be simpler, but we are not 100% yet.

As JD said:

> Not sure what's easier to maintain long-term.

### 👎 Update traffic tracking

Tracking traffic to distinguish between crates and downloads becomes more difficult because you need to take into account the path of the request (`/crates/` and `/downloads/`).

This means that if we have dashboards that track the traffic of `static.crates.io` to check the traffic of crates, we need to update them to differentiate between `https://static.crates.io/crates/` and `https://static.crates.io/downloads/`.


## Clarification

In zulip, JD said:

> We need to create a new CloudFront distribution.

My question is: Was Fastly CDN considered here? 🤔

## What I need from you

- Let me know what I got wrong
- Tell me if I'm missing some pro or con (I tried to capture everything discussed in zulip).
- (optional) your opinions about these pros and cons

**Comment by jdno** [comment]
Thanks for putting this summary together! :)

Tracking traffic isn't really a concern for us, especially since the expected volume of the download archives will be tiny compared to the volume of crate downloads.

The biggest advantage for the first approach is in my opinion that the bucket and its distribution will be in the same AWS account, making it easier for the crates.io team to make and test changes, and to observe the correct behavior of the distribution in production. Access to resources in the `legacy` account is more restricted and more difficult to grant.

Out of both options, the second one seems to be the cleanest. We'll need to come up with a good name (aka URL path) for the download archives and create a policy that grants CloudFront in the `legacy` account access to the S3 buckets in `crates-io-{staging,production}`, but those are solvable issues. And on the flip side, we still serve static content from the same `static.crates.io` domain.

**Comment by MarcoIeni** [comment]
I also agree that the second option seems the cleanest. Since Pietro originally proposed this, probably we can consider we have a consensus unless someone else wants to share their opinion as well 👍

I'll start looking into the implementation.
In the meantime, let's discuss the URL path. I.e. what to put in `static.crates.io/<here>/`. Some options that comes to mind:
- `downloads`
- `statistics`
- `stats`

`downloads` is my preferred option because that's how they are called in the frontend:

<img width="944" alt="Screenshot 2024-07-19 at 14 30 42" src="https://github.com/user-attachments/assets/239d61d6-df38-41dc-ada5-4549d9bfe2cb">

**Comment by MarcoIeni** [comment]
Some implementation considerations.

From my understanding, we need to add a new origin [here](https://github.com/rust-lang/simpleinfra/blob/afe279882f2f6c901bb6f1d1766613f75fe2d089/terragrunt/modules/crates-io/cloudfront-static.tf#L67) that points to [this](https://github.com/rust-lang/simpleinfra/blob/afe279882f2f6c901bb6f1d1766613f75fe2d089/terragrunt/modules/crates-io-downloads-archive/main.tf) s3 bucket.
This means that the `crates-io` module should refer to the bucket in the `crates-io-downloads-archive` terraform module.
Should we edit the `crates-io-downloads-archive` module so that its [output](https://developer.hashicorp.com/terraform/language/modules/syntax#accessing-module-output-values) contains the s3 bucket URL? In this way, the `crates-io` can use the URL in the cloudfront origin (so that we avoid hardcoding it).

From my research, to allow cloudfront to access s3 in another account we need to create:
- a Origin Access Control (OAC) so that CloudFront can access the S3 bucket in the other account. Note: OAC is the evolution of OAI. Apparently AOC is supported by our provider [version](https://registry.terraform.io/providers/hashicorp/aws/4.32.0/docs/resources/cloudfront_origin_access_control) and we are already using it for [docs.rs](https://github.com/rust-lang/simpleinfra/blob/afe279882f2f6c901bb6f1d1766613f75fe2d089/terraform/docs-rs/static-cloudfront.tf#L42) 👍 
- an S3 bucket policy to grant `cloudfront.amazonaws.com` read-only access to the bucket as explained [here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html).

Let me know what you think and correct me if I got something wrong 👍

**Comment by MarcoIeni** [comment]
Here's the summary of my sync call with JD:

- `downloads` might be confusing since people might think you can download crates there, not crates statistics. JD prefers `statistics`. Let's ask the crates.io team 👍

[ ] make sure the origin is only used for that specific path. Maybe it's in the behavior.

Probably having module dependencies doesn't work in this case, because the two modules use different authentication methods (legacy vs sso). So let's just hardcode s3 URLs in this case.

**Comment by MarcoIeni** [comment]
blocked by https://github.com/rust-lang/crates.io/pull/9180

**Comment by MarcoIeni** [comment]
```
$ aws s3 ls s3://staging-crates-io/archive/version-downloads/ --summarize | grep "Total"
Total Objects: 191
   Total Size: 6088

$ aws s3 ls s3://crates-io/archive/version-downloads/ --summarize | grep "Total"
Total Objects: 3459
   Total Size: 2780121850

$ aws s3 ls s3://staging-crates-io-downloads-archive --summarize --profile crates-io-staging | grep "Total"
Total Objects: 190
   Total Size: 6060

$ aws s3 ls s3://crates-io-downloads-archive --summarize --profile crates-io-prod | grep "Total"
Total Objects: 3458
   Total Size: 2772212251
```

**Comment by MarcoIeni** [comment]
- [ ] We need to serve `index.html` from the CDN
https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/archiving.20.60version_downloads.60.20to.20S3/near/455739337

**Comment by MarcoIeni** [comment]
PR ready to be reviewed https://github.com/rust-lang/simpleinfra/pull/469

**Comment by MarcoIeni** [comment]
Remaining tasks:

- [ ] https://github.com/rust-lang/simpleinfra/pull/471
- [ ] https://github.com/rust-lang/simpleinfra/pull/469

**Comment by MarcoIeni** [comment]
Done https://static.crates.io/archive/version-downloads/ 🎉
