### ISSUE TITLE
Update Terraform providers

### ISSUE THREAD

**Issue by jdno** [rust-lang/simpleinfra#437]
Most of the Terraform providers in `/terraform` and `/terragrunt` are out-of-date, since we tend to only upgrade them when a new feature is required.

Updating some providers, e.g. the AWS provider, has proven to be quite difficult since it is used in almost all modules. This has frequently caused issues due to mismatching versions, and essentially requires us to update all modules one-by-one. When reviewing our modules, there might be opportunities to remove dependencies by copying their resources into the "main" module. While this duplicates some configuration, it will make maintenance and updates much easier in the future.

Another consideration is that we use a few deprecated resources or attributes, and updating the providers will most likely mean that we need to refactor some of our configuration. This might be a good opportunity to also install a tool like [tflint](https://github.com/terraform-linters/tflint) to ensure the updated configuration follows best practices.

## Tasks

- [x] Update providers in `terraform/bastion` https://github.com/rust-lang/simpleinfra/pull/499
- [x] Update providers in `terraform/bors` https://github.com/rust-lang/simpleinfra/pull/509
- [x] Update providers in `terraform/crater` https://github.com/rust-lang/simpleinfra/pull/556
- [x] Update providers in `terraform/crates-io-heroku-metrics` https://github.com/rust-lang/simpleinfra/pull/508
- [x] Update providers in `terraform/dev-desktops` https://github.com/rust-lang/simpleinfra/pull/519
- [x] Update providers in `terraform/discord-mods-bot` https://github.com/rust-lang/simpleinfra/pull/507
- [x] Update providers in `terraform/dns` https://github.com/rust-lang/simpleinfra/pull/503
- [x] Update providers in `terraform/dns-delegation` https://github.com/rust-lang/simpleinfra/pull/498
- [x] Update providers in `terraform/docs-rs` https://github.com/rust-lang/simpleinfra/pull/506
- [x] Update providers in `terraform/domain-redirects` https://github.com/rust-lang/simpleinfra/pull/518
- [x] Update providers in `terraform/fastly-exporter` https://github.com/rust-lang/simpleinfra/pull/512
- [x] Update providers in `terraform/monitorbot` https://github.com/rust-lang/simpleinfra/pull/510
- [x] Update providers in `terraform/playground` https://github.com/rust-lang/simpleinfra/pull/502
- [x] Update providers in `terraform/rds-databases` https://github.com/rust-lang/simpleinfra/pull/497
- [x] Update providers in `terraform/releases` https://github.com/rust-lang/simpleinfra/pull/500
- [x] Update providers in `terraform/rust-forge` https://github.com/rust-lang/simpleinfra/pull/517
- [x] Update providers in `terraform/rust-log-analyzer` https://github.com/rust-lang/simpleinfra/pull/511
- [x] Update providers in `terraform/rustc-ci` https://github.com/rust-lang/simpleinfra/pull/513/
- [x] Update providers in `terraform/rustc-perf` https://github.com/rust-lang/simpleinfra/pull/545
- [x] Update providers in `terraform/shared` https://github.com/rust-lang/simpleinfra/pull/527
- [x] Update providers in `terraform/team-members-access` https://github.com/rust-lang/simpleinfra/pull/514
- [x] Update providers in `terraform/team-members-datadog` https://github.com/rust-lang/simpleinfra/pull/515
- [x] Update providers in `terraform/team-members-fastly` https://github.com/rust-lang/simpleinfra/pull/479
- [x] Update providers in `terraform/team-repo` https://github.com/rust-lang/simpleinfra/pull/501
- [ ] Update providers in `terragrunt/modules/acm-certificate`
- [x] Update providers in `terragrunt/modules/aws-lambda` https://github.com/rust-lang/simpleinfra/pull/533
- [x] Update providers in `terragrunt/modules/aws-organization` https://github.com/rust-lang/simpleinfra/pull/535
- [x] Update providers in `terragrunt/modules/bastion` (doesn't contain any version)
- [x] Update providers in `terragrunt/modules/bors` https://github.com/rust-lang/simpleinfra/pull/523
- [x] Update providers in `terragrunt/modules/common` https://github.com/rust-lang/simpleinfra/pull/524
- [x] Update providers in `terragrunt/modules/crates-io` https://github.com/rust-lang/simpleinfra/pull/532
- [x] Update providers in `terragrunt/modules/crates-io-downloads-archive` (we deleted it)
- [x] Update providers in `terragrunt/modules/crates-io-logs` https://github.com/rust-lang/simpleinfra/pull/504
- [x] Update providers in `terragrunt/modules/datadog-aws` https://github.com/rust-lang/simpleinfra/pull/522
- [x] Update providers in `terragrunt/modules/datadog-fastly` https://github.com/rust-lang/simpleinfra/pull/529
- [x] Update providers in `terragrunt/modules/dev-desktops-azure`
- [x] Update providers in `terragrunt/modules/dns-zone` doesn't have versions
- [ ] Update providers in `terragrunt/modules/docs-rs`
- [ ] Update providers in `terragrunt/modules/ecr-repo`
- [ ] Update providers in `terragrunt/modules/ecs-app`
- [ ] Update providers in `terragrunt/modules/ecs-cluster`
- [ ] Update providers in `terragrunt/modules/ecs-service`
- [ ] Update providers in `terragrunt/modules/ecs-task`
- [x] Update providers in `terragrunt/modules/fastly-tls-subscription` https://github.com/rust-lang/simpleinfra/pull/537
- [ ] Update providers in `terragrunt/modules/gha-iam-user`
- [x] Update providers in `terragrunt/modules/gha-oidc-role` doesn't have versions
- [x] Update providers in `terragrunt/modules/release-distribution` https://github.com/rust-lang/simpleinfra/pull/533
- [x] Update providers in `terragrunt/modules/resource-group` https://github.com/rust-lang/simpleinfra/pull/461
- [x] Update providers in `terragrunt/modules/rustup` https://github.com/rust-lang/simpleinfra/pull/534
- [x] Update providers in `terragrunt/modules/sync-team` we want to delete this.
- [ ] Update providers in `terragrunt/modules/vpc`
- [x] Update providers in `terragrunt/modules/win-rustup-rs` https://github.com/rust-lang/simpleinfra/pull/531
- [x] Update providers in `terragrunt/modules/wiz` https://github.com/rust-lang/simpleinfra/pull/452

## Related Issues

- #376 is currently blocked by this issue, since version 4.x of the AWS provider does not support a more recent runtime.

**Comment by MarcoIeni** [comment]
I upgraded everything except docs-rs-staging, which is unused. 

To verify, you can run: `infratk graph --clipboard --outdated --min-versions hashicorp/aws=5.64.0`. (see infratk [here](https://github.com/MarcoIeni/infratk)).

I created https://github.com/rust-lang/simpleinfra/issues/557 for the warnings 👍

**Comment by MarcoIeni** [comment]
![graphviz (8)](https://github.com/user-attachments/assets/53c683c4-d11f-43eb-a3cf-4499573c6347)
Here's the graph I generated with infratk if you want to have a look 👍
the "✅" symbol means that the module is up-to-date
